name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Trigger only when a version tag is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install Poetry
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      # Step 4: Configure Poetry for PyPI
      - name: Configure Poetry
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      # Step 5: Install dependencies
      - name: Install dependencies
        run: poetry install

      # Step 6: Build and publish to PyPI
      - name: Publish to PyPI
        run: poetry publish --build
